# Assembles a vcpkg-shaped libvlc archive from a built VLC tree.
#
#   .\pack.ps1 -VlcSrc C:\Source\vlc -Arch x64 -Version 3.0.23 -OutFile libvlc-3.0.23-x64-uwp.zip
#
# Only the plugin selection is a list: the build produces about 320 plugins and Unigram loads 36,
# so plugins.txt names them. Everything else is taken wholesale from the built tree.
param(
    # The VLC checkout, holding the build output and the generated plugin caches.
    [string]$VlcSrc = (Join-Path $PSScriptRoot '..\..\vlc'),
    [Parameter(Mandatory = $true)][ValidateSet('x64', 'arm64')][string]$Arch,
    [Parameter(Mandatory = $true)][string]$Version,     # e.g. 3.0.23
    [Parameter(Mandatory = $true)][string]$OutFile
)
$ErrorActionPreference = 'Stop'

$buildDir = if ($Arch -eq 'x64') { 'win64-uwp' } else { 'winarm64-uwp' }
$tree     = Join-Path $VlcSrc "$buildDir\vlc-$Version"
if (-not (Test-Path $tree)) { throw "No built VLC tree at $tree -- run build.ps1 first" }

$staging = Join-Path ([System.IO.Path]::GetTempPath()) ("libvlc-" + [System.Guid]::NewGuid().ToString('N'))
function Stage([string]$Relative) { $p = Join-Path $staging $Relative; New-Item -ItemType Directory -Force -Path $p | Out-Null; return $p }

# Headers and import libraries: whole directories, no selection.
Copy-Item (Join-Path $tree 'sdk\include\*') (Stage 'include') -Recurse
Copy-Item (Join-Path $tree 'sdk\lib\*.lib') (Stage 'lib')

# vlc.lib and vlccore.lib are aliases with no matching DLL, and the .pc files would drag pkgconf
# and an msys download into any build that consumed them.
Remove-Item (Join-Path $staging 'lib\vlc.lib'), (Join-Path $staging 'lib\vlccore.lib') -ErrorAction SilentlyContinue

$bin = Stage 'bin'
Copy-Item (Join-Path $tree 'libvlc.dll') $bin
Copy-Item (Join-Path $tree 'libvlccore.dll') $bin

# The plugins keep their directory structure: their relative paths are recorded in the generated
# plugins.dat cache, so flattening them would invalidate it.
$pluginRoot = Stage 'share\libvlc\plugins'
$wanted = Get-Content (Join-Path $PSScriptRoot 'plugins.txt') |
          Where-Object { $_.Trim() -and -not $_.StartsWith('#') }
foreach ($rel in $wanted) {
    $src = Join-Path $tree "plugins\$($rel.Replace('/', '\'))"
    if (-not (Test-Path $src)) { throw "Missing plugin: $src" }
    $dst = Join-Path $pluginRoot $rel.Replace('/', '\')
    New-Item -ItemType Directory -Force -Path (Split-Path $dst) | Out-Null
    Copy-Item $src $dst
}

# Generated by plugins-cache.ps1 after the build; without it VLC scans every plugin on launch.
$cache = Join-Path $VlcSrc "plugins-$Arch.dat"
if (-not (Test-Path $cache)) { throw "Missing plugin cache: $cache -- run plugins-cache.ps1" }
Copy-Item $cache (Join-Path $pluginRoot 'plugins.dat')

# LGPL obliges shipping the licence with the binaries; vcpkg also expects one.
$copying = Join-Path $VlcSrc 'COPYING.LIB'
if (Test-Path $copying) { Copy-Item $copying (Join-Path $staging 'copyright') }

if (Test-Path $OutFile) { Remove-Item $OutFile }
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory($staging, $OutFile, 'Optimal', $false)
$count = (Get-ChildItem $staging -Recurse -File).Count
Remove-Item $staging -Recurse -Force

"{0}  {1:N1} MB  {2} files" -f (Split-Path $OutFile -Leaf), ((Get-Item $OutFile).Length / 1MB), $count
"SHA512 {0}" -f (Get-FileHash $OutFile -Algorithm SHA512).Hash.ToLower()
